baseURL = 'https://yusufsaka007.github.io/'
languageCode = 'en-us'
title = "viv4ldi's blog"
theme = 'hackerspace'

[markup]
  [markup.highlight]
    style = 'github-dark'
    lineNos = true
    lineNumbersInTable = false
    guessSyntax = true
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  tag = "tags"

[params]
  author = "viv4ldi"
  description = "Bug bounty hunting, CTF writeups, and security research."
  bio = "Bug bounty hunter. CTF player. CPTS certified."
  github = "yusufsaka007"
  linkedin = "yusufsaka007"
  twitter = "yusufsaka007"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "bug-bounty"
    url = "/bug-bounty/"
    weight = 2
  [[menu.main]]
    name = "ctf"
    url = "/ctf/"
    weight = 3
  [[menu.main]]
    name = "certs"
    url = "/certs/"
    weight = 4
  [[menu.main]]
    name = "misc"
    url = "/misc/"
    weight = 5
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 6
